# file      : tests/basic/buildfile
# copyright : Copyright (c) 2009-2019 Code Synthesis Tools CC
# license   : Unicode License; see accompanying LICENSE file

import libs = libicuuc%lib{icuuc}

exe{driver}: {h c}{*} $libs testscript
