# file      : libicuio/buildfile
# license   : Unicode License; see accompanying LICENSE file

import intf_libs  = libicui18n%lib{icui18n}
import intf_libs += libicuuc%lib{icuuc}

lib{icuio}: io/hxx{**} io/cxx{**} $intf_libs

# Build options.
#
cxx.poptions  += -DU_IO_IMPLEMENTATION

cxx.poptions =+ "-I$src_base/io"

obja{*}: cxx.poptions += -DU_STATIC_IMPLEMENTATION

cxx.coptions += $common_cc_coptions     \
                $common_cxx_coptions    \
                $lib_cc_coptions

if ($cxx.class == 'msvc')
  cxx.coptions += /wd4996 # Disable warnings that pop up with /W3.

# Export options.
#
lib{icuio}:
{
  cc.export.poptions = "-I$src_base/io"
  cc.export.libs     = $intf_libs
}

cxx.loptions += $lib_cc_loptions
cxx.libs += $common_cxx_libs

liba{icuio}: cc.export.poptions += -DU_STATIC_IMPLEMENTATION

# See bootstrap.build for details.
#
if $version.pre_release
  lib{icuio}: bin.lib.version = @"-$version.project_id"
else
  lib{icuio}: bin.lib.version = @"-$abi_version_major" linux@"$abi_version"

# Install headers from the io/unicode/ subdirectory only.
#
hxx{*}:            install = false
io/unicode/hxx{*}: install = include/unicode/
