# file      : tests/basic/buildfile
# license   : Unicode License; see accompanying LICENSE file

import libs  = libicuio%lib{icuio}
import libs += libicuuc%lib{icuuc}

exe{driver}: {hxx cxx}{*} $libs testscript
