# file      : tests/basic/buildfile
# license   : Unicode License; see accompanying LICENSE file

import libs  = libicui18n%lib{icui18n}
import libs += libicuuc%lib{icuuc}

exe{driver}: {hxx cxx}{*} $libs testscript
